### ISSUE TITLE
How can i run this project? 

### ISSUE THREAD

**Issue by xlisp** [district0x/district0x-facts-db#1]
```bash

➜  district0x-facts-db git:(master) ✗ clj -A:build-index-server
Error building classpath. nil
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at clojure.core$re_matcher.invokeStatic(core.clj:4856)
	at clojure.core$re_find.invokeStatic(core.clj:4898)
	at clojure.core$re_find.invoke(core.clj:4898)
	at clojure.tools.deps.alpha.util.maven$version_range_QMARK_.invokeStatic(maven.clj:250)
	at clojure.tools.deps.alpha.util.maven$version_range_QMARK_.invoke(maven.clj:248)
	at clojure.tools.deps.alpha.extensions.maven$eval703$fn__706.invoke(maven.clj:46)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at clojure.tools.deps.alpha$canonicalize_deps$fn__1136.invoke(alpha.clj:69)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8140.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at clojure.tools.deps.alpha$canonicalize_deps.invokeStatic(alpha.clj:68)
	at clojure.tools.deps.alpha$canonicalize_deps.invoke(alpha.clj:66)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:236)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:217)
	at clojure.tools.deps.alpha.script.make_classpath2$create_classpath.invokeStatic(make_classpath2.clj:55)
	at clojure.tools.deps.alpha.script.make_classpath2$create_classpath.invoke(make_classpath2.clj:47)
	at clojure.tools.deps.alpha.script.make_classpath2$run_core.invokeStatic(make_classpath2.clj:81)
	at clojure.tools.deps.alpha.script.make_classpath2$run_core.invoke(make_classpath2.clj:72)
	at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:101)
	at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:95)
	at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:146)
	at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:118)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
➜  district0x-facts-db git:(master) ✗
```

**Comment by jpmonettas** [comment]
Hi @chanshunli, this is an abandoned project, we are following a different path at district0x. I still think there are some interesting ideas to explore deeper here.

That weird error was caused by a typo in deps.edn for which I just pushed a fix for. The project isn't currently compiling because it depends on a version of cljs-web3-next that doesn't exist anymore (not even in github) since the name was used to host a different project we wrote from scratch. That said it shouldn't be hard to migrate it to cljs-web3-next current version so if you are really interested in trying this stuff I can help you with that.

This project came out from this experiments https://github.com/district0x/d0xperiments which currently suffer from the same compilation issues.

**Comment by xlisp** [comment]
@jpmonettas  Thanks for your help. because  i need use the indexedDB for datascript. 
 like this code: 

```clojure

(ns district0x-facts-db.indexeddb
  (:require [clojure.core.async :as async]))

(defonce facts-db (atom nil))

(defn init-indexed-db! []
  (set! (.-indexedDB js/window) (or (.-indexedDB js/window)
                                    (.-mozIndexedDB js/window)
                                    (.-webkitIndexedDB js/window)
                                    (.-msIndexedDB js/window)))
  (let [req (js/window.indexedDB.open "FactsDB")
        out-ch (async/chan)]
    (set! (.-onupgradeneeded req) (fn [e]
                                    (let [db (-> e .-target .-result)
                                          store (.createObjectStore db "facts" #js {:keyPath "factId" :autoIncrement true})]
                                      (.createIndex store "blockNum" "blockNum" #js {:unique false})
                                      (set! (-> store .-transaction .-oncomplete)
                                            (fn [oce]
                                              (reset! facts-db db))))))
    (set! (.-onsuccess req) (fn [e]
                              (let [db (-> e .-target .-result)]
                                (reset! facts-db db)
                                (async/put! out-ch true))))
    out-ch))

``` 
and i have finded https://github.com/district0x/cljs-web3-next, 

```diff

diff --git a/deps.edn b/deps.edn
index 783a7e3..4ad10de 100644
--- a/deps.edn
+++ b/deps.edn
@@ -1,6 +1,6 @@
 {:deps {org.clojure/clojure       {:mvn/version "1.9.0"}
         org.clojure/clojurescript {:mvn/version "1.10.439"}
-        cljs-web3-next            {:local/root "/home/jmonetta/my-projects/district0x/cljs-web3-next"}
+        cljs-web3-next            {:local/root "/Users/clojure/cljs-web3-next"}
         org.clojure/core.async    {:mvn/version "0.4.474"}
         cljs-ajax                 {:mvn/version "0.7.5-patched"}
         datascript                {:mvn/version "0.16.6"}

```
but tonsky asked me (https://github.com/tonsky/datascript/issues/358), `indexedDB is async, which is not supported by DataScript`. 
Can you help me? how it's work ?
